# -*- coding: utf-8 -*-
"""Google search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PJineh_hk5sYCoK7QE0IRuRDEsoXtPiq
"""

pip install google-api-python-client

import json

"""Test this out Only """

from googleapiclient.discovery import build
my_api_key = "AIzaSyCWJ9-zXoQr53YWxT9hHoGX4DGRsWNx_kQ"
my_cse_id = "f048ca8e92d064c34"

# Load the JSON file containing questions
with open('/content/tables.json') as f:
    questions = json.load(f)

def google_search(search_term, api_key, cse_id, **kwargs):
    service = build("customsearch", "v1", developerKey=api_key)
    res = service.cse().list(q=search_term, cx=cse_id, **kwargs).execute()
    return res

i=0
for i in range(len(questions)):

  result = google_search(questions[i]['subquestion'], my_api_key, my_cse_id)
  for values in (result['items']):
   print(values['snippet'])
   print("\n")

   print(values['htmlSnippet'])
   print("\n")
   print("\n")
   print("\n")
   
# print(result.values())

print

"""the following code wasn't working

"""

import requests
import json

# Load the JSON file containing questions
with open('/content/tables.json') as f:
    questions = json.load(f)

# Define the API endpoint and parameters
url = 'https://cse.google.com/cse?cx=f048ca8e92d064c34'
params = {
    'q': '',
    'cx': 'f048ca8e92d064c34',
    'key': 'AIzaSyCWJ9-zXoQr53YWxT9hHoGX4DGRsWNx_kQ',
    'num': 1
}

# Iterate over each question and make a request to the API
for q in questions:
    params['q'] = q  # Set the 'q' parameter to the current question
    response = requests.get(url, params=params)  # Make a GET request to the API

    # print(type(response))
    results = response.json()  # Extract the search results from the response
    # Process the search results as needed
    print(results)